### ISSUE TITLE
Tips for troubleshooting?

### ISSUE THREAD

**Issue by ChristianWeyer** [jsakamoto/Toolbelt.AspNetCore.CssLiveReloader#1]
Hi!

As mentioned in the repo of your other tool (https://github.com/jsakamoto/Toolbelt.Blazor.DevServer.WithCssLiveReloader), I am trying to get your tool working in a Blazor WASM assembly hosted in ASP.NET Core.

![image](https://user-images.githubusercontent.com/888718/77104323-232cf980-6a1c-11ea-9f56-6f5bc75a0224.png)

I have added the middleware as instructed in the README. However, I cannot see any changes in the client.

Any tips on how to troubleshoot this?
Thanks.

**Comment by jsakamoto** [comment]
@ChristianWeyer Thank you for your report!

Could you try to "Empty cache and hard refresh" once?

For example, in a chromium-based browser, try follow steps.

1. Open developer console. (Ctrl + Shift + I)
2. Long press "Refresh" button on the browser window.
3. Chose  "Empty cache and hard refresh" options in the popup menu.

![image](https://user-images.githubusercontent.com/95908/77125451-24484000-6a89-11ea-9464-862ff696ea13.png)

If you still cannot see any changes in the client after the above steps, could you attach your project files as a zip archive file into this issue? and, please let me know your OS platform and which browser product did you try it.

Thanks!

**Comment by ChristianWeyer** [comment]
Thanks for the hints.
Indeed it seems it was related to a missing `"useWebAssemblyDebugging": true,` in project properties.

Could that be?

**Comment by jsakamoto** [comment]
> Indeed it seems it was related to a missing "useWebAssemblyDebugging": true, in project properties.
> Could that be?

Hum... I think, there is no dependency with my CSS live reloading implementation and "useWebAssemblyDebugging" configuration.

I tried 2 cases that adding to `"useWebAssemblyDebugging": true` and adding `"useWebAssemblyDebugging": false` in `launchSettings.json`, but CSS live reloading worked fine on both cases on my PC. 

![image](https://user-images.githubusercontent.com/95908/77167959-59d94180-6afa-11ea-9511-ba44bfd4df58.png)

Could you check the below points?

1. Is the HTML document injected "/Toolbelt.AspNetCore.CssLiveReloader/script.min.js"?  
![image](https://user-images.githubusercontent.com/95908/77168375-103d2680-6afb-11ea-8521-3281cff0ad98.png)
2. Is there a network log that is connection to "/Toolbelt.AspNetCore.CssLiveReloader/EventSource" (the type is  "eventsource") successfully?
![image](https://user-images.githubusercontent.com/95908/77168557-5d20fd00-6afb-11ea-9108-b6fd0e60423b.png)
3. Is there a network log that is HTTP POST request to "/Toolbelt.AspNetCore.CssLiveReloader/WatchRequest" with JSON payload which contains CSS file's URL?  
![image](https://user-images.githubusercontent.com/95908/77168759-b8eb8600-6afb-11ea-8997-16fafb524d06.png)

**Comment by ChristianWeyer** [comment]
It all works now as you describe. I still think it has to do with caching, maybe.
Thanks for your help!

**Comment by jsakamoto** [comment]
@ChristianWeyer Good news! Happy coding :)
